### PR TITLE
Update README.md, how to add sidebar toc?

### PR DESCRIPTION
**Pull request by cnmade**

### CODE REVIEW

**Comment by cnmade** [comment]
The rendered html with sidebar toc looks like :

image



No addition html js file , only a small piece of css file and small configuration

that's all.

**Comment by badboy** [comment]
Thanks for the contribution! Calling out how to style the ToC is actually a good idea, though I will edit how that's presented in the readme.

**Comment by cnmade** [comment]
ok. for real rust book document demo:

image


https://cnmade.github.io/book/ch01-01-installation.html

**Comment by onqtam** [comment]
woah, this is cool!

would it be possible to not have the sidebar TOC as an element that overlaps with the book contents, but instead as a new panel on the right - like the panel on the left?

and would it be possible to generate the TOC in the left panel as well - where the chapters are listed?

**Pull request closed without merging**
